name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      -
        name: Build and push Docker Images
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/flask-app-swarm:${{github.sha}}
      -
        name: Deploy to Swarm Manager
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 14921
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script:
            export DOCKER_HOST=tcp://4.tcp.eu.ngrok.io:14921
            docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/flask-app-swarm:${{ github.sha }} <nom_du_service>
